--- # MODULE EC2_METRiC EXAMPLE
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  vars_files:
  - files/awscred.yaml
  tasks:
  - name: create basic cpu alarm
    ec2_metric_alarm:
      aws_access_key: "{{aws_id}}"
      aws_secret_key: "{{aws_key}}"
      region: "{{aws_region}}"
      state: present
      name: firstalarmtest
      metric: "CPUUtilization"
      namespace: "AWS/EC2"
      statistic: Average
      comparison: ">="
      threshold: 25.0
      period: 300
      evaluation_periods: 6
      unit: "Percent"
      description: "This alarm files when cpu is greater than 25% for 30 minutes"
      dimensions: {'InstanceID':'i-042921d7c4591dcd0'}
