--- # ec2 start,stop,terminate module use example
- hosts: loacalhost
  connection: local
  remote_user: abhi
  become: yes
  gather_facts: no
  vars_files:
  - files/awscred.yaml
  tasks:
  - name: manage the state of an instance
    ec2:
    aws_access_key: "{{aws_id}}"
    aws_secret_key: "{{aws_key}}"
    region: us-east-1
    instance_ids: i-0a9fabd442674db78
    state: runnig

