--- # ec3_key module example creating and deleting
- hosts: localhost
  connection: local
  remote_user: abhi
  become: yes
  gather_facts: no
  vars_files:
  - files/awscred.yaml
  tasks:
  - name: create a new key pair - testkeypair
    ec2_key:
      aws_access_key: "{{aws_id}}"
      aws_secret_key: "{{aws_key}}"
      name: testkeypair
      region: us-east-1
      state: present  # state: absent
