--- # MODULE EC2_VOL EXAMPLE
- hosts: localhost
  connection: local
  remote_user: abhi
  become: yes
  gather_facts: no
  vars_files:
  - files/awscred.yaml
  tasks:
  - name: Creating a new volume and attach to running instance
    ec2_vol:
      aws_access_key: "{{aws_id}}"
      aws_secret_key: "{{aws_key}}"
      region: "{{aws_region}}"
      instance: i-0af47286ac777e2b5
      state: list
    register: volume_result
  - debug: msg={{ volume_result }}
