--- # EC2_AMI Example for creating a basic AMI template from an existing image
- hosts: localhost
  connection: local
  remote_user: abhi
  become: yes
  gather_facts: no
  vars_files:
  - files/awscred.yaml
  tasks:
  - name: More Advanced Provisioning of AMI from our instances
    ec2_ami:
      aws_access_key: "{{aws_id}}"
      aws_secret_key: "{{aws_key}}"
      region: us-east-1
      instance_id: i-08508a3c6927dda01
      wait: no
      name: mynewami2
      tags:
        Name: MynewAMI2
        Service: TestAMIservice2
      device_mapping:
        - device_name: /dev/sdb1
          size: 100
          delete_on_termination: true
          volume_type: gp2
    register: instance
