--- # MODULE EC2_REMOTE_FACTS EXAMPLE
- hosts: localhost
  connection: local
  remote_user: abhi
  become: yes
  gather_facts: no
  vars_files:
  - files/awscred.yaml
  tasks:
  - name: Gather facts of all running ec2 instances
    ec2_remote_facts:
      aws_access_key: "{{aws_id}}"
      aws_secret_key: "{{aws_key}}"
      region: "{{aws_region}}"
    register: remote_facts
  - debug: msg={{ remote_facts }}

