--- # My First YAML Playbook for Ansible
- hosts: ubuntu:linux
  user: abhi
  sudo: yes
  connection: ssh
  vars:
    playbook_version: 0.1B
  tasks:
    - name: Installing docker in the Distribution (RedHat/CentOS)
      command: yum -y install docker
      when: ansible_os_family == "RedHat"
    - name: Installing docker in the Distribution (Debian/Ubuntu)
      command: apt-get -y install docker
      when: ansible_os_family == "Debian"
      notify: Restart Docker
    - name: giving docker deamon access
      command: usermod -aG docker abhi
    - name: pulling ubuntu image
      command: docker pull ubuntu
    - name: pulling nginx image
      command: docker pull nginx
  handlers:
    - name: Restart Docker
      action: service name=docker state=restarted
