--- # My First YAML Playbook for Ansible
- hosts: apacheweb
  user: abhi
  sudo: yes
  connection: ssh
  gather_facts: no
  vars: 
    playbook_version: 0.1b
  vars_files:
    - conf/copyright.yaml
    - conf/webdefaults.yaml
  vars_prompt:
    - name: web_domain
      prompt: Web Domain
  tasks:
    - name: Install Lynx Web Browser
      action: apt name=lynx state=installed
    - name: Check for Telnet Clinet
      action: apt name=telnet state=absent
