--- # managing by including other yaml files

- hosts: impellenttech1.mylabserver.com 
  user: abhi
  sudo: yes
  connection: ssh
  gather_facts: yes
  tasks:
  - include: packages/yum.yaml
    when: ansible_os_family == "Redhat"
  - include: commands/commands.yaml
  handlers:
  - include: handler/handlers.yaml
