--- # provison of Kubernetes cluster on AWS infrastructure
- name: Provision Of AWS Infrastructure
  hosts: localhost
  connection: local
  remote_user: abhi
  become_method: sudo
  gather_facts: no
  tasks:
  - include: instances.yaml
    wait_for: timeout=120
# Provisioning Kubernetes Master On AWS Infrastructure
- name: Provision Of Kubernetes Master On AWS Infrastructure
  hosts: tag_Name_KubernetesMaster
  connection: ssh
  remote_user: ubuntu
  become: yes
  gather_facts: yes
  roles:
    - Kubernetes_master

# Provisioning Kubernetes Master On AWS Infrastructure
- name: Provision Of Kubernetes Nodes On AWS Infrastructure
  hosts: tag_Name_KubernetesNode
  connection: ssh
  remote_user: ubuntu
  become: yes
  gather_facts: yes
  roles:
    - Kubernetes_node
