--- # Provisioning Kubernetes Master On AWS Infrastructure
- name: Provision Of Kubernetes Master On AWS Infrastructure
  hosts: tag_Name_KubernetesMaster
  connection: ssh
  remote_user: ubuntu
  become: yes
  gather_facts: yes
  roles:
    - Kubernetes_master

# Provisioning Kubernetes Nodes On AWS Infrastructure
- name: Provision Of Kubernetes Nodes On AWS Infrastructure
  hosts: tag_Name_KubernetesNode
  connection: ssh
  remote_user: ubuntu
  become: yes
  gather_facts: yes
  roles:
    - Kubernetes_nodes
