--- # Main file gettings tasks together based on systems distribution
- name: Installing prerequired packages for DEBIAN/UBUNTU distribution
  include: roles/Kubernetes_nodes/tasks/apt_packages.yaml

- name: Installing prerequired packages for REDHAT?CENTOS distribution
  import_tasks: yum_packages.yaml
  when: ansible_distribution == 'Redhat'
