--- # Main file gettings tasks together based on systems distribution
- name: Installing prerequired packages for DEBIAN/UBUNTU distribution
  include: roles/Kubernetes/tasks/apt_packages.yaml

- name: Installing prerequired packages for REDHAT?CENTOS distribution
  import_tasks: yum_packages.yaml
  when: ansible_distribution == 'Redhat'

- name: Initiating Kubernetes Master
  include: roles/Kubernetes/tasks/kubeadm_init.yaml
  include: roles/Kubernetes/tasks/master.yaml
