--- # initiating kubeadm
- name: Making Directory
  command: mkdir -p $HOME/.kube
- name: Getting cofig file up
  command: sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
- name: Getting Permissions done
  file:
    path: $HOME/.kube/config
    mode: 0600
