--- # initiating kubeadm
- name: first command
  command: sudo cp /etc/kubernetes/admin.conf $HOME/
- name: second command
  command: sudo chown $(id -u):$(id -g) $HOME/admin.conf
- name: third command
  command: export KUBECONFIG=$HOME/admin.conf
