--- # MODULE EC2_GROUP EXAMPLE
- hosts: localhost
  connection: local
  remote_user: abhi
  become: yes
  gather_facts: no
  vars_files:
  - files/awscred.yaml
  tasks:
  - name: Basic security group creation
    ec2_group:
      aws_access_key: "{{aws_id}}"
      aws_secret_key: "{{aws_key}}"
      region: "{{aws_region}}"
      name:  Mytestgroup
      description: This is the ec2-group demo
      vpc_id: vpc-0bde0c73
      rules:
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
      rules_egress:
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
