--- # EC2 MOSULE PROVISIONING EXAMPLE
- hosts: localhost
  connection: local
  remote_user: abhi
  become: yes
  gather_facts: no
  vars_files:
  - files/awscred.yaml
  tasks:
  - name: Basic provisioning of two t2.micro instances
    ec2:
      aws_access_key: "{{aws_id}}"
      aws_secret_key: "{{aws_key}}"
      region: us-east-2 
      image: ami-10547475
      instance_type: t2.micro
      keypair: Vangari1993
      group: My Security Group
      count: 1

